const ORDER_SET_TYPE = "ORDER_SET_TYPE";
const CATEGORY_LIST_REQUEST = "CATEGORY_LIST_REQUEST";
const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS";
const CATEGORY_LIST_FAIL = "CATEGORY_LIST_FAIL";
const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";
const ORDER_ADD_ITEM = "ORDER_ADD_ITEM";
const ORDER_REMOVE_ITEM = "ORDER_REMOVE_ITEM";
const ORDER_CLEAR = "ORDER_CLEAR";
const ORDER_SET_PAYMENT_TYPE = "ORDER_SET_PAYMENT_TYPE";

export {
  ORDER_SET_TYPE,
  CATEGORY_LIST_REQUEST,
  CATEGORY_LIST_SUCCESS,
  CATEGORY_LIST_FAIL,
  PRODUCT_LIST_REQUEST,
  PRODUCT_LIST_SUCCESS,
  PRODUCT_LIST_FAIL,
  ORDER_ADD_ITEM,
  ORDER_REMOVE_ITEM,
  ORDER_CLEAR,
  ORDER_SET_PAYMENT_TYPE
};