const ORDER_SET_TYPE = "ORDER_SET_TYPE";
const CATEGORY_LIST_REQUEST = "CATEGORY_LIST_REQUEST";
const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS";
const CATEGORY_LIST_FAIL = "CATEGORY_LIST_FAIL";

export {
  ORDER_SET_TYPE,
  CATEGORY_LIST_REQUEST,
  CATEGORY_LIST_SUCCESS,
  CATEGORY_LIST_FAIL
};